### ISSUE TITLE
update class names for bootstrap 3

### ISSUE THREAD

**Issue by thecristen** [ptb/flexgrid#2]
So Bootstrap no longer uses the span6, span8, etc names for the layout. Any plans on updating this?

**Comment by homerjam** [comment]
+1

**Comment by ptb** [comment]
I've updated the project. The flexgrid-reorder.css file is now a drop-in replacement for the final Bootstrap 3 grid. If you don't need the push and pull classes, you can save a chunk of bandwidth and use the basic flexgrid.css file instead.
